name: enr-environment
channels:
  - conda-forge
dependencies:
  - pygeoprocessing
  - natcap.invest
  - hazelbean
  - numpy
  - scikit-learn
  - statsmodels
  - xlrd
  - gdal
  - geopandas
  - matplotlib
  - pandas
  - dask
